# Generated by Django 4.1.7 on 2023-03-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=15, null=True)),
                ('cliente', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30, null=True)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('fechaEntrega', models.DateTimeField(verbose_name='Fecha Entrega')),
                ('descripcion', models.TextField(max_length=100)),
                ('tipo', models.CharField(choices=[('COTIZACION', 'COTIZACION'), ('ORDEN DE TRABAJO', 'ORDEN DE TRABAJO')], max_length=20)),
                ('tipoTrabajo', models.CharField(choices=[('GRAN-FORMATO', 'GRAN-FORMATO'), ('CORTE-LASER Y GRABADO', 'CORTE-LASER Y GRABADO'), ('IMPRESIONES', 'IMPRESIONES'), ('PUBLICIDAD', 'PUBLICIDAD')], max_length=30)),
                ('estado', models.CharField(choices=[('COTIZAR', 'COTIZAR'), ('COTIZADO', 'COTIZADO'), ('EN PROCESO', 'EN PROCESO'), ('LISTO', 'LISTO'), ('ENTREGADO', 'ENTREGADO')], max_length=20)),
            ],
            options={
                'verbose_name': 'trabajo',
                'verbose_name_plural': 'trabajos',
            },
        ),
    ]
