# Generated by Django 4.1.7 on 2023-03-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
